### ISSUE TITLE
В чём смысл этой строки?

### ISSUE THREAD

**Issue by coursar** [powerlord1990/HW4.2.-HouseService#11]
https://github.com/powerlord1990/HW4.2.-HouseService/blob/7770dc0c65575accd0ea822d11fa8bf9302d95c4/src/main/java/ru/itpark/service/HouseService.java#L13

**Comment by powerlord1990** [comment]
вы в предыдущем ишью говорили что лучше копировать исходный лист домов и сортировать уже копию. вот я таким образом и скопировал его и далее все манипуляции делал с ним

**Comment by powerlord1990** [comment]
прошу прощения не додумался. сделал в попыхах
   private List<House> houses = new ArrayList<>();

    private List<House> sortByPrice() {
        List<House> houseNew = new ArrayList<>(houses);
        houseNew.sort(Comparator.comparing(House::getPrice));
        return houseNew;
    } 
исправил на этот вариант
